defmodule MinhaCasaAi.Integrations.Langfuse.DefaultPrompts do
  @moduledoc """
  Snapshot fallback when Langfuse is unreachable. Generated by `mix langfuse.sync_prompts`.
  """

  @snapshot_path "priv/langfuse/prompts.snapshot.json"

  def get(name) when is_binary(name) do
    case snapshot()[name] do
      %{"prompt" => prompt} = entry when is_binary(prompt) ->
        {:ok,
         %{
           name: name,
           version: Map.get(entry, "version", 0),
           prompt: prompt,
           type: Map.get(entry, "type", "text")
         }}

      _ ->
        fallback_from_definitions(name)
    end
  end

  defp fallback_from_definitions(name) do
    alias MinhaCasaAi.Integrations.Langfuse.PromptDefinitions

    case PromptDefinitions.get(name) do
      %{"prompt" => prompt} = entry when is_binary(prompt) ->
        {:ok,
         %{
           name: name,
           version: 1,
           prompt: String.trim(prompt),
           type: Map.get(entry, "type", "text")
         }}

      _ ->
        {:error, :prompt_not_found}
    end
  end

  def all_names do
    snapshot() |> Map.keys() |> Enum.sort()
  end

  defp snapshot do
    path = Application.app_dir(:minha_casa_ai, @snapshot_path)

    case File.read(path) do
      {:ok, body} ->
        case Jason.decode(body) do
          {:ok, map} when is_map(map) -> map
          _ -> %{}
        end

      _ ->
        %{}
    end
  end
end
