import type { Imovel } from "$lib/anuncios/types";

export const INITIAL_DEMO_LISTINGS: Imovel[] = [
  {
    id: "demo-1",
    titulo: "Casa Alto Padrão - Jurerê Internacional",
    endereco: "Rua das Palmeiras, 123 - Jurerê Internacional, Florianópolis",
    m2Totais: 450,
    m2Privado: 320,
    quartos: 4,
    suites: 2,
    banheiros: 4,
    garagem: 3,
    preco: 2850000,
    precoM2: 2850000 / 320,
    piscina: true,
    porteiro24h: null,
    academia: null,
    vistaLivre: null,
    piscinaTermica: null,
    link: null,
    tipoImovel: "casa",
    starred: true,
    visited: false,
    strikethrough: false,
    createdAt: new Date().toISOString(),
    addedAt: "2026-01-20"
  },
  {
    id: "demo-2",
    titulo: "Apartamento Vista Mar - Beira Mar Norte",
    endereco: "Av. Jornalista Rubens de Arruda Ramos, 1000 - Centro, Florianópolis",
    m2Totais: 210,
    m2Privado: 180,
    quartos: 3,
    suites: 3,
    banheiros: 4,
    garagem: 2,
    preco: 3200000,
    precoM2: 3200000 / 180,
    piscina: false,
    porteiro24h: null,
    academia: null,
    vistaLivre: null,
    piscinaTermica: null,
    link: null,
    tipoImovel: "apartamento",
    starred: false,
    visited: true,
    strikethrough: false,
    createdAt: new Date().toISOString(),
    addedAt: "2026-01-22"
  },
  {
    id: "demo-3",
    titulo: "Sobrado Moderno - Novo Campeche",
    endereco: "Rua dos Surfistas, 50 - Campeche, Florianópolis",
    m2Totais: 180,
    m2Privado: 150,
    quartos: 3,
    suites: 1,
    banheiros: 2,
    garagem: 1,
    preco: 1250000,
    precoM2: 1250000 / 150,
    piscina: true,
    porteiro24h: null,
    academia: null,
    vistaLivre: null,
    piscinaTermica: null,
    link: null,
    tipoImovel: "casa",
    starred: false,
    visited: false,
    strikethrough: true,
    discardedReason: "Preço acima do mercado para a região",
    createdAt: new Date().toISOString(),
    addedAt: "2026-01-25"
  }
];
