import type { Property } from "$lib/listings/types";

export const INITIAL_DEMO_LISTINGS: Property[] = [
  {
    id: "demo-1",
    title: "Casa Alto Padrão - Jurerê Internacional",
    address: "Rua das Palmeiras, 123 - Jurerê Internacional, Florianópolis",
    totalAreaM2: 450,
    privateAreaM2: 320,
    bedrooms: 4,
    suites: 2,
    bathrooms: 4,
    parkingSpots: 3,
    constructionYear: null,
    price: 2850000,
    pricePerM2: 2850000 / 320,
    features: { pool: true },
    sourceUrl: null,
    propertyType: "house",
    starred: true,
    visited: false,
    strikethrough: false,
    createdAt: new Date().toISOString(),
    addedAt: "2026-01-20"
  },
  {
    id: "demo-2",
    title: "Apartamento Vista Mar - Beira Mar Norte",
    address: "Av. Jornalista Rubens de Arruda Ramos, 1000 - Centro, Florianópolis",
    totalAreaM2: 210,
    privateAreaM2: 180,
    bedrooms: 3,
    suites: 3,
    bathrooms: 4,
    parkingSpots: 2,
    constructionYear: null,
    price: 3200000,
    pricePerM2: 3200000 / 180,
    features: { pool: false },
    sourceUrl: null,
    propertyType: "apartment",
    starred: false,
    visited: true,
    strikethrough: false,
    createdAt: new Date().toISOString(),
    addedAt: "2026-01-22"
  },
  {
    id: "demo-3",
    title: "Sobrado Moderno - Novo Campeche",
    address: "Rua dos Surfistas, 50 - Campeche, Florianópolis",
    totalAreaM2: 180,
    privateAreaM2: 150,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 1,
    constructionYear: null,
    price: 1250000,
    pricePerM2: 1250000 / 150,
    features: { pool: true },
    sourceUrl: null,
    propertyType: "house",
    starred: false,
    visited: false,
    strikethrough: true,
    discardedReason: "Preço acima do mercado para a região",
    createdAt: new Date().toISOString(),
    addedAt: "2026-01-25"
  }
];
